apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-api
  template:
    metadata:
      labels:
        app: hello-world-api
    spec:
      containers:
        - name: hello-world-api
          image: hello-world-api:v1
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: default
spec:
  type: NodePort
  selector:
    app: hello-world-api
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
